name: nsw-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - voila>=0.3.0
  - ipywidgets>=8.0
  - ipyleaflet>=0.17.0
  - geopandas>=0.13.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - folium>=0.14.0
  - matplotlib>=3.7.0
  - requests
  - shapely
  - pip
  - pip:
    - contextily
    - qgrid2